---
abstract: 'Interface to perls parser variables'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  B::Hooks::EndOfScope: 0
  B::Hooks::OP::Check: 0
  Test::Exception: 0
configure_requires:
  B::Hooks::OP::Check: 0
  ExtUtils::Depends: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: B-Hooks-Parser
no_index:
  directory:
    - inc
    - t
requires:
  B::Hooks::OP::Check: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
